default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # username: 'postgres'
    # docker時変更
  host: localhost
  # port: 5432


development:
  <<: *default
  database: new_todo_app_development


test:
  <<: *default
  database: new_todo_app_test

production:
  <<: *default
  database: new_todo_app_production
  username: kanta
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
